### PR TITLE
Added optional "flags" parameter to most functions

### PR DESCRIPTION
**Pull request by jamesbirkett**
Needed to use a few gitty commands with flags in a way that wasn't allowed for, so added flags parameters to most functions (only excluding those that I can't think of a reasonable use-case that would require the use of flags).

@gordonwritescode - I hope I haven't just ignored a conscious decision to limit the use of flags.

### CODE REVIEW

**Comment by gordonwritescode** [comment]
@jamesbirkett nope! looks good! thanks! will bump and publish shortly

**Comment by gordonwritescode** [comment]
published gitty@3.3.0 to npm

**Comment by jamesbirkett** [comment]
@gordonwritescode - I don't know whether this was to do with my version of node or something, but while running the test all the ...Sync functions failed with `undefined is not a function`.

node is up to date and I even tried installing node-legacy in case `execSync` ran differently in some way.

I wanted to just make sure I'd not broken anything but even vanilla master was failing.

Thoughts?

**Comment by gordonwritescode** [comment]
@jamesbirkett strange, travis reported success, and running the tests locally against node@0.5.0 and node@0.12.7 yields success as well.

I'm on Debian Sid and Travis is on Ubuntu - what platform are you on?

**Comment by jamesbirkett** [comment]
@gordonwritescode I'm on Ubuntu 10.4 on node@0.10.25. As long as it's working for Travis I'm happy that I've not broken anything, that's the main thing.

**Comment by jamesbirkett** [comment]
@gordonwritescode  - symlink to /usr/bin/node was pointing to the wrong version. All's good; apologies for confusion.

**Comment by gordonwritescode** [comment]
ah, very good!

**Pull request merged**
