### PR TITLE
Passing Repository to Command to allow access to path and gitpath fields.

### PR DESCRIPTION
**Pull request by waynebloss**
Here are the changes that I discussed in issue #51.

Some known issues:

- The JsDoc info on [this line](https://github.com/gordonwritescode/gitty/compare/master...waynebloss:master#diff-b26080cc6f2472dce354dbedffc64d57R12) is not complete. It should be changed to `{string|Repository}` at the least I think.

- All tests passed for me except for the clone test because I have no git server running. I could change the url and test again I guess but I didn't want to waste any time figuring it out since you will most likely run tests yourself.

Thanks. Let me know if there is anything that you do not like.

### CODE REVIEW

**Comment by gordonwritescode** [comment]
Cool! I'll review, test, and merge this weekend. Much appreciated!

**Comment by waynebloss** [comment]
I forgot to add the `gitpath` param to the main `Gitty` function in `/index.js`, so I fixed that in another commit.

If you decide later to accept multiple options to the main `Gitty` function or the `Repository` constructor, you can just rename the `gitpath` param to `options` where `gitpath` would be the default option when a string is passed instead of an options object.

**Comment by waynebloss** [comment]
Also, I did not write any new tests for this - sorry about that! I am not even using this library yet, but I am strongly leaning towards using it instead of nodegit since this seems much cleaner and simpler to deploy and maintain.

**Comment by gordonwritescode** [comment]
No worries. Tested - no regressions. Everything looks good to me!

How about adding yourself to the `contributors` in `package.json`, and I'll add a simple test that set's the `gitpath` to something bogus and expect a failure to make sure that `Command` is in fact using that property to execute commands, then I'll bump the version to `3.3.1` and merge this in!

**Comment by waynebloss** [comment]
No problem. Thanks!

**Pull request merged**
